/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RouteProgressRouteImport } from './routes/route-progress'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountContributionsRouteImport } from './routes/account.contributions'
import { Route as AccountMapRouteImport } from './routes/account.map'
import { Route as AccountSavedRouteImport } from './routes/account.saved'
import { Route as AccountStampsRouteImport } from './routes/account.stamps'
import { Route as AccountStoriesRouteImport } from './routes/account.stories'
import { Route as AccountVisitedRouteImport } from './routes/account.visited'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityCreateRouteImport } from './routes/community.create'
import { Route as CommunityFeaturedRouteImport } from './routes/community.featured'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AccountSettingsIndexRouteImport } from './routes/account.settings.index'
import { Route as AccountSettingsLanguageRouteImport } from './routes/account.settings.language'
import { Route as AccountSettingsNotificationsRouteImport } from './routes/account.settings.notifications'
import { Route as AccountSettingsPrivacyRouteImport } from './routes/account.settings.privacy'
import { Route as ArtworkIdIndexRouteImport } from './routes/artwork.$id.index'
import { Route as ArtworkIdArRouteImport } from './routes/artwork.$id.ar'
import { Route as ArtworkIdArtistRouteImport } from './routes/artwork.$id.artist'
import { Route as ArtworkIdAudioRouteImport } from './routes/artwork.$id.audio'
import { Route as ArtworkIdDirectionsRouteImport } from './routes/artwork.$id.directions'
import { Route as ArtworkIdReflectRouteImport } from './routes/artwork.$id.reflect'
import { Route as ArtworkIdScanRouteImport } from './routes/artwork.$id.scan'
import { Route as CommunityCollectionIdRouteImport } from './routes/community.collection.$id'
import { Route as CommunityForumIdRouteImport } from './routes/community.forum.$id'
import { Route as CommunityJournalIdRouteImport } from './routes/community.journal.$id'
import { Route as ArtworkIdStoryStoryIdRouteImport } from './routes/artwork.$id.story.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteProgressRoute = RouteProgressRouteImport.update({
  id: '/route-progress',
  path: '/route-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountContributionsRoute = AccountContributionsRouteImport.update({
  id: '/account/contributions',
  path: '/account/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMapRoute = AccountMapRouteImport.update({
  id: '/account/map',
  path: '/account/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/account/saved',
  path: '/account/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountStampsRoute = AccountStampsRouteImport.update({
  id: '/account/stamps',
  path: '/account/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountStoriesRoute = AccountStoriesRouteImport.update({
  id: '/account/stories',
  path: '/account/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVisitedRoute = AccountVisitedRouteImport.update({
  id: '/account/visited',
  path: '/account/visited',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCreateRoute = CommunityCreateRouteImport.update({
  id: '/community/create',
  path: '/community/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeaturedRoute = CommunityFeaturedRouteImport.update({
  id: '/community/featured',
  path: '/community/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account/settings/',
  path: '/account/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsLanguageRoute = AccountSettingsLanguageRouteImport.update({
  id: '/account/settings/language',
  path: '/account/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsNotificationsRoute =
  AccountSettingsNotificationsRouteImport.update({
    id: '/account/settings/notifications',
    path: '/account/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountSettingsPrivacyRoute = AccountSettingsPrivacyRouteImport.update({
  id: '/account/settings/privacy',
  path: '/account/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdIndexRoute = ArtworkIdIndexRouteImport.update({
  id: '/artwork/$id/',
  path: '/artwork/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdArRoute = ArtworkIdArRouteImport.update({
  id: '/artwork/$id/ar',
  path: '/artwork/$id/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdArtistRoute = ArtworkIdArtistRouteImport.update({
  id: '/artwork/$id/artist',
  path: '/artwork/$id/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdAudioRoute = ArtworkIdAudioRouteImport.update({
  id: '/artwork/$id/audio',
  path: '/artwork/$id/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdDirectionsRoute = ArtworkIdDirectionsRouteImport.update({
  id: '/artwork/$id/directions',
  path: '/artwork/$id/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdReflectRoute = ArtworkIdReflectRouteImport.update({
  id: '/artwork/$id/reflect',
  path: '/artwork/$id/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdScanRoute = ArtworkIdScanRouteImport.update({
  id: '/artwork/$id/scan',
  path: '/artwork/$id/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCollectionIdRoute = CommunityCollectionIdRouteImport.update({
  id: '/community/collection/$id',
  path: '/community/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityForumIdRoute = CommunityForumIdRouteImport.update({
  id: '/community/forum/$id',
  path: '/community/forum/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityJournalIdRoute = CommunityJournalIdRouteImport.update({
  id: '/community/journal/$id',
  path: '/community/journal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdStoryStoryIdRoute = ArtworkIdStoryStoryIdRouteImport.update({
  id: '/artwork/$id/story/$storyId',
  path: '/artwork/$id/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/route-progress': typeof RouteProgressRoute
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/contributions': typeof AccountContributionsRoute
  '/account/map': typeof AccountMapRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/stamps': typeof AccountStampsRoute
  '/account/stories': typeof AccountStoriesRoute
  '/account/visited': typeof AccountVisitedRoute
  '/community/create': typeof CommunityCreateRoute
  '/community/featured': typeof CommunityFeaturedRoute
  '/account/': typeof AccountIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/settings/language': typeof AccountSettingsLanguageRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/privacy': typeof AccountSettingsPrivacyRoute
  '/artwork/$id/ar': typeof ArtworkIdArRoute
  '/artwork/$id/artist': typeof ArtworkIdArtistRoute
  '/artwork/$id/audio': typeof ArtworkIdAudioRoute
  '/artwork/$id/directions': typeof ArtworkIdDirectionsRoute
  '/artwork/$id/reflect': typeof ArtworkIdReflectRoute
  '/artwork/$id/scan': typeof ArtworkIdScanRoute
  '/community/collection/$id': typeof CommunityCollectionIdRoute
  '/community/forum/$id': typeof CommunityForumIdRoute
  '/community/journal/$id': typeof CommunityJournalIdRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/artwork/$id/': typeof ArtworkIdIndexRoute
  '/artwork/$id/story/$storyId': typeof ArtworkIdStoryStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/route-progress': typeof RouteProgressRoute
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/contributions': typeof AccountContributionsRoute
  '/account/map': typeof AccountMapRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/stamps': typeof AccountStampsRoute
  '/account/stories': typeof AccountStoriesRoute
  '/account/visited': typeof AccountVisitedRoute
  '/community/create': typeof CommunityCreateRoute
  '/community/featured': typeof CommunityFeaturedRoute
  '/account': typeof AccountIndexRoute
  '/community': typeof CommunityIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/settings/language': typeof AccountSettingsLanguageRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/privacy': typeof AccountSettingsPrivacyRoute
  '/artwork/$id/ar': typeof ArtworkIdArRoute
  '/artwork/$id/artist': typeof ArtworkIdArtistRoute
  '/artwork/$id/audio': typeof ArtworkIdAudioRoute
  '/artwork/$id/directions': typeof ArtworkIdDirectionsRoute
  '/artwork/$id/reflect': typeof ArtworkIdReflectRoute
  '/artwork/$id/scan': typeof ArtworkIdScanRoute
  '/community/collection/$id': typeof CommunityCollectionIdRoute
  '/community/forum/$id': typeof CommunityForumIdRoute
  '/community/journal/$id': typeof CommunityJournalIdRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/artwork/$id': typeof ArtworkIdIndexRoute
  '/artwork/$id/story/$storyId': typeof ArtworkIdStoryStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/route-progress': typeof RouteProgressRoute
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/contributions': typeof AccountContributionsRoute
  '/account/map': typeof AccountMapRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/stamps': typeof AccountStampsRoute
  '/account/stories': typeof AccountStoriesRoute
  '/account/visited': typeof AccountVisitedRoute
  '/community/create': typeof CommunityCreateRoute
  '/community/featured': typeof CommunityFeaturedRoute
  '/account/': typeof AccountIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/settings/language': typeof AccountSettingsLanguageRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/privacy': typeof AccountSettingsPrivacyRoute
  '/artwork/$id/ar': typeof ArtworkIdArRoute
  '/artwork/$id/artist': typeof ArtworkIdArtistRoute
  '/artwork/$id/audio': typeof ArtworkIdAudioRoute
  '/artwork/$id/directions': typeof ArtworkIdDirectionsRoute
  '/artwork/$id/reflect': typeof ArtworkIdReflectRoute
  '/artwork/$id/scan': typeof ArtworkIdScanRoute
  '/community/collection/$id': typeof CommunityCollectionIdRoute
  '/community/forum/$id': typeof CommunityForumIdRoute
  '/community/journal/$id': typeof CommunityJournalIdRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/artwork/$id/': typeof ArtworkIdIndexRoute
  '/artwork/$id/story/$storyId': typeof ArtworkIdStoryStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/mcp'
    | '/route-progress'
    | '/routes'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/contributions'
    | '/account/map'
    | '/account/saved'
    | '/account/stamps'
    | '/account/stories'
    | '/account/visited'
    | '/community/create'
    | '/community/featured'
    | '/account/'
    | '/community/'
    | '/.mcp/invoke-tool/$tool'
    | '/account/settings/language'
    | '/account/settings/notifications'
    | '/account/settings/privacy'
    | '/artwork/$id/ar'
    | '/artwork/$id/artist'
    | '/artwork/$id/audio'
    | '/artwork/$id/directions'
    | '/artwork/$id/reflect'
    | '/artwork/$id/scan'
    | '/community/collection/$id'
    | '/community/forum/$id'
    | '/community/journal/$id'
    | '/account/settings/'
    | '/artwork/$id/'
    | '/artwork/$id/story/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/mcp'
    | '/route-progress'
    | '/routes'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/contributions'
    | '/account/map'
    | '/account/saved'
    | '/account/stamps'
    | '/account/stories'
    | '/account/visited'
    | '/community/create'
    | '/community/featured'
    | '/account'
    | '/community'
    | '/.mcp/invoke-tool/$tool'
    | '/account/settings/language'
    | '/account/settings/notifications'
    | '/account/settings/privacy'
    | '/artwork/$id/ar'
    | '/artwork/$id/artist'
    | '/artwork/$id/audio'
    | '/artwork/$id/directions'
    | '/artwork/$id/reflect'
    | '/artwork/$id/scan'
    | '/community/collection/$id'
    | '/community/forum/$id'
    | '/community/journal/$id'
    | '/account/settings'
    | '/artwork/$id'
    | '/artwork/$id/story/$storyId'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/mcp'
    | '/route-progress'
    | '/routes'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/contributions'
    | '/account/map'
    | '/account/saved'
    | '/account/stamps'
    | '/account/stories'
    | '/account/visited'
    | '/community/create'
    | '/community/featured'
    | '/account/'
    | '/community/'
    | '/.mcp/invoke-tool/$tool'
    | '/account/settings/language'
    | '/account/settings/notifications'
    | '/account/settings/privacy'
    | '/artwork/$id/ar'
    | '/artwork/$id/artist'
    | '/artwork/$id/audio'
    | '/artwork/$id/directions'
    | '/artwork/$id/reflect'
    | '/artwork/$id/scan'
    | '/community/collection/$id'
    | '/community/forum/$id'
    | '/community/journal/$id'
    | '/account/settings/'
    | '/artwork/$id/'
    | '/artwork/$id/story/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  RouteProgressRoute: typeof RouteProgressRoute
  RoutesRoute: typeof RoutesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AccountContributionsRoute: typeof AccountContributionsRoute
  AccountMapRoute: typeof AccountMapRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AccountStampsRoute: typeof AccountStampsRoute
  AccountStoriesRoute: typeof AccountStoriesRoute
  AccountVisitedRoute: typeof AccountVisitedRoute
  CommunityCreateRoute: typeof CommunityCreateRoute
  CommunityFeaturedRoute: typeof CommunityFeaturedRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AccountSettingsLanguageRoute: typeof AccountSettingsLanguageRoute
  AccountSettingsNotificationsRoute: typeof AccountSettingsNotificationsRoute
  AccountSettingsPrivacyRoute: typeof AccountSettingsPrivacyRoute
  ArtworkIdArRoute: typeof ArtworkIdArRoute
  ArtworkIdArtistRoute: typeof ArtworkIdArtistRoute
  ArtworkIdAudioRoute: typeof ArtworkIdAudioRoute
  ArtworkIdDirectionsRoute: typeof ArtworkIdDirectionsRoute
  ArtworkIdReflectRoute: typeof ArtworkIdReflectRoute
  ArtworkIdScanRoute: typeof ArtworkIdScanRoute
  CommunityCollectionIdRoute: typeof CommunityCollectionIdRoute
  CommunityForumIdRoute: typeof CommunityForumIdRoute
  CommunityJournalIdRoute: typeof CommunityJournalIdRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
  ArtworkIdIndexRoute: typeof ArtworkIdIndexRoute
  ArtworkIdStoryStoryIdRoute: typeof ArtworkIdStoryStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-progress': {
      id: '/route-progress'
      path: '/route-progress'
      fullPath: '/route-progress'
      preLoaderRoute: typeof RouteProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/contributions': {
      id: '/account/contributions'
      path: '/account/contributions'
      fullPath: '/account/contributions'
      preLoaderRoute: typeof AccountContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/map': {
      id: '/account/map'
      path: '/account/map'
      fullPath: '/account/map'
      preLoaderRoute: typeof AccountMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/account/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/stamps': {
      id: '/account/stamps'
      path: '/account/stamps'
      fullPath: '/account/stamps'
      preLoaderRoute: typeof AccountStampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/stories': {
      id: '/account/stories'
      path: '/account/stories'
      fullPath: '/account/stories'
      preLoaderRoute: typeof AccountStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/visited': {
      id: '/account/visited'
      path: '/account/visited'
      fullPath: '/account/visited'
      preLoaderRoute: typeof AccountVisitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/create': {
      id: '/community/create'
      path: '/community/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof CommunityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/featured': {
      id: '/community/featured'
      path: '/community/featured'
      fullPath: '/community/featured'
      preLoaderRoute: typeof CommunityFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/language': {
      id: '/account/settings/language'
      path: '/account/settings/language'
      fullPath: '/account/settings/language'
      preLoaderRoute: typeof AccountSettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/notifications': {
      id: '/account/settings/notifications'
      path: '/account/settings/notifications'
      fullPath: '/account/settings/notifications'
      preLoaderRoute: typeof AccountSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/privacy': {
      id: '/account/settings/privacy'
      path: '/account/settings/privacy'
      fullPath: '/account/settings/privacy'
      preLoaderRoute: typeof AccountSettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/': {
      id: '/artwork/$id/'
      path: '/artwork/$id'
      fullPath: '/artwork/$id/'
      preLoaderRoute: typeof ArtworkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/ar': {
      id: '/artwork/$id/ar'
      path: '/artwork/$id/ar'
      fullPath: '/artwork/$id/ar'
      preLoaderRoute: typeof ArtworkIdArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/artist': {
      id: '/artwork/$id/artist'
      path: '/artwork/$id/artist'
      fullPath: '/artwork/$id/artist'
      preLoaderRoute: typeof ArtworkIdArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/audio': {
      id: '/artwork/$id/audio'
      path: '/artwork/$id/audio'
      fullPath: '/artwork/$id/audio'
      preLoaderRoute: typeof ArtworkIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/directions': {
      id: '/artwork/$id/directions'
      path: '/artwork/$id/directions'
      fullPath: '/artwork/$id/directions'
      preLoaderRoute: typeof ArtworkIdDirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/reflect': {
      id: '/artwork/$id/reflect'
      path: '/artwork/$id/reflect'
      fullPath: '/artwork/$id/reflect'
      preLoaderRoute: typeof ArtworkIdReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/scan': {
      id: '/artwork/$id/scan'
      path: '/artwork/$id/scan'
      fullPath: '/artwork/$id/scan'
      preLoaderRoute: typeof ArtworkIdScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/collection/$id': {
      id: '/community/collection/$id'
      path: '/community/collection/$id'
      fullPath: '/community/collection/$id'
      preLoaderRoute: typeof CommunityCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/forum/$id': {
      id: '/community/forum/$id'
      path: '/community/forum/$id'
      fullPath: '/community/forum/$id'
      preLoaderRoute: typeof CommunityForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/journal/$id': {
      id: '/community/journal/$id'
      path: '/community/journal/$id'
      fullPath: '/community/journal/$id'
      preLoaderRoute: typeof CommunityJournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id/story/$storyId': {
      id: '/artwork/$id/story/$storyId'
      path: '/artwork/$id/story/$storyId'
      fullPath: '/artwork/$id/story/$storyId'
      preLoaderRoute: typeof ArtworkIdStoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  RouteProgressRoute: RouteProgressRoute,
  RoutesRoute: RoutesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AccountContributionsRoute: AccountContributionsRoute,
  AccountMapRoute: AccountMapRoute,
  AccountSavedRoute: AccountSavedRoute,
  AccountStampsRoute: AccountStampsRoute,
  AccountStoriesRoute: AccountStoriesRoute,
  AccountVisitedRoute: AccountVisitedRoute,
  CommunityCreateRoute: CommunityCreateRoute,
  CommunityFeaturedRoute: CommunityFeaturedRoute,
  AccountIndexRoute: AccountIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AccountSettingsLanguageRoute: AccountSettingsLanguageRoute,
  AccountSettingsNotificationsRoute: AccountSettingsNotificationsRoute,
  AccountSettingsPrivacyRoute: AccountSettingsPrivacyRoute,
  ArtworkIdArRoute: ArtworkIdArRoute,
  ArtworkIdArtistRoute: ArtworkIdArtistRoute,
  ArtworkIdAudioRoute: ArtworkIdAudioRoute,
  ArtworkIdDirectionsRoute: ArtworkIdDirectionsRoute,
  ArtworkIdReflectRoute: ArtworkIdReflectRoute,
  ArtworkIdScanRoute: ArtworkIdScanRoute,
  CommunityCollectionIdRoute: CommunityCollectionIdRoute,
  CommunityForumIdRoute: CommunityForumIdRoute,
  CommunityJournalIdRoute: CommunityJournalIdRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
  ArtworkIdIndexRoute: ArtworkIdIndexRoute,
  ArtworkIdStoryStoryIdRoute: ArtworkIdStoryStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
